### ISSUE TITLE
Support for other clients, than default telegram?

### ISSUE THREAD

**Issue by wazerstar** [Wokzy/blum-bot#14]
The normal telegram client kinda is meh

There's another version called [AyuGram](https://github.com/AyuGram/AyuGramDesktop)

There's also 2 other active github versions prior to this one

[forkgram](https://github.com/forkgram/tdesktop)

[TDesktop-x64](https://github.com/TDesktop-x64/tdesktop)

 I changed the

APPLICATION_NAME = 'TelegramDesktop'

to

APPLICATION_NAME = 'AyuGram'

It detects the window but does not play.

Can you make some kind of support for parameters to detect other clients or at least incorporate this one :)?

**Comment by Wokzy** [comment]
Send me some fullsize screenshots, where game window is opened and I will try to rearrange parameters

**Comment by wazerstar** [comment]
> Send me some fullsize screenshots, where game window is opened and I will try to rearrange parameters

![IaiaXVD](https://github.com/user-attachments/assets/ced598ce-c672-4647-833f-9ec7e55133da)

**Comment by wazerstar** [comment]
> Send me some fullsize screenshots, where game window is opened and I will try to rearrange parameters

I figured out how to find the correct pixels, and its also catching all flowers, but its not clicking play/continue when I put in X amount of games?

I have to start it each time
