### ISSUE TITLE
Feature request: Make paramter to fail % of flower drop.

### ISSUE THREAD

**Issue by wazerstar** [Wokzy/blum-bot#15]
Something like

main.py -drop 10-25

where -drop would let 10-25% of flowers slip through the game ie. not catching them catch between 10-25% of all flowers dropping to make it look more human,

using -drop 10 could be just a plain static of 10% drop in all games playing.

If its not possible to know how much that will drop it could be like drop every flower between x amount of seconds or something like that?

What do you think?

**Comment by Wokzy** [comment]
Good idea, will try to implement
