### ISSUE TITLE
$Dogs drop

### ISSUE THREAD

**Issue by hhjoo** [Wokzy/blum-bot#16]
Hi , would you update the bot to catch $Dogs ?

**Comment by Wokzy** [comment]
I don't have enough referrals on my account, so $Dogs are not availible for me, so I couldn't adopt script for it

**Comment by hhjoo** [comment]
Can i help you by anyway like getting for responses or something like that ?

**Comment by Wokzy** [comment]
Make some pure screenshots of gamewindow when you are playing and $dogs are dropping, so I could rearrange some parameters, the way my script will recognize $dogs

**Comment by Wokzy** [comment]
According to the latest news, dogs drop will be available on Monday for every single user, so I will adopt my script as soon as it goes live

**Comment by hhjoo** [comment]
There's some issues with Blum service right now, I'll provide you what you want just when it comes back to work.

**Comment by hhjoo** [comment]
![Screenshot_٢٠٢٤١٠١٨-١١٢٠٢٦_Telegram](https://github.com/user-attachments/assets/eb6ce439-c5b7-42e6-88c2-781de020b4d5)

**Comment by hhjoo** [comment]
This is some screenshots from Android device 

https://imgur.com/a/DVDtpDK

**Comment by hhjoo** [comment]
And this from windows vps 2019

https://imgur.com/a/OP3z1o8

**Comment by hhjoo** [comment]
Any update?

**Comment by Wokzy** [comment]
Seems like Blum team still hasn't made dogs drop for everyone. But using your screen shots I'll try to implement dogs catching

**Comment by hhjoo** [comment]
It's done for me cause i won't be eligible for next round . GG

**Comment by Wokzy** [comment]
Just in case, I made an update, now autoclicker collects $dogs. I'm sorry for long delays.
