### ISSUE TITLE
Replay the game?

### ISSUE THREAD

**Issue by hhjoo** [Wokzy/blum-bot#25]
Play just once not clicking on play again like i need to scroll down to see the dialog of play again how I'll fix it?

**Comment by hhjoo** [comment]
Using win 22 vps

**Comment by SomeAkther2003** [comment]
**Adding the code below will solve the scroll problem. You have to place them in the reight place**

import pyautogui

def scroll_to_bottom():
    """Scroll to the bottom of the screen"""
    pyautogui.scroll(-10000)

# Scroll down before clicking the play button
                scroll_to_bottom()
                time.sleep(1)  # Allow some time for the scrolling to complete
                mouse.move(x, y, absolute=True)
                mouse.click(button='left')
                wait_running_game(camera, timeout=5.5)

**Comment by Wokzy** [comment]
Better using `mouse.wheel(-1000)`, it will be much faster, than `pyautogui`.
