### ISSUE TITLE
Didnt 

### ISSUE THREAD

**Issue by codenewinsight** [Wokzy/blum-bot#3]
![Screenshot 2024-06-19 041735](https://github.com/Wokzy/blum-bot/assets/31296734/b070e3b2-8791-4b26-be90-e42e61884882)

could you please check again script

**Comment by Wokzy** [comment]
One crucial thing about executing script: don't move game window, because it's position on screen is static for my script. I'll fix it in future

**Comment by r4z0rz** [comment]
I've got the same issue, i tried not moving it as you suggested but that doesn't seem to work, is there a specific resolution that this is tailored to?
