### ISSUE TITLE
Cant play

### ISSUE THREAD

**Issue by adiprrassetyo** [Wokzy/blum-bot#31]
![image](https://github.com/user-attachments/assets/72d7b89f-aa4e-41c1-a575-333a88b8b84f)

How, 
in previous update, i tried it, and could, and now this is it

**Comment by Wokzy** [comment]
Try to disable notifications in telegram and relaunch it. Don't do anything except opening Blum game and then run the script. Error, according to your screenshot, is related to Windows driver, so I can't do anything but offer you to run Blum app "carefully"
