### ISSUE TITLE
Awoiding mines?

### ISSUE THREAD

**Issue by kalpak79** [Wokzy/blum-bot#32]
How can i fix the trouble with bombs? because when the mouse clicking on green (idk smth) it could be double click on a bomb behind the green blumies

**Comment by Wokzy** [comment]
I'm sorry, but unfortunately It can't be fixed, because if my script detects green "flower" it clicks on it. It can't be determined wether the bomb is hidden behind the "flower" unless pedict it's movement somehow.
But you can try, the code is open source)
