### ISSUE TITLE
Blum update

### ISSUE THREAD

**Issue by Fakhrillo** [Wokzy/blum-bot#33]
Hi Wokzy, I'm a big fan of your work! Thanks to your script, I've been mining a lot lately. I noticed that Blum recently updated the game for the New Year holidays. Could you please update the bot? Thank you!

**Comment by kaskabayev** [comment]
hey @Wokzy , yes, the game updated, here is the screenshot.

![image](https://github.com/user-attachments/assets/d62a1c9a-b6a8-47f2-9410-67ccdf51269e)

**Comment by Alimrd200001** [comment]
the game's new update and the significant increase in rewards. It would be very helpful if you could release the update before the current game mode ends. I'm a big fan of your work. thanks alot

**Comment by Wokzy** [comment]
Hello, Guys! Update is ready
