### ISSUE TITLE
xmas event has been changed!

### ISSUE THREAD

**Issue by kalpak79** [Wokzy/blum-bot#34]
now program with flag --xmas not working

**Comment by ProgMan01** [comment]
Works, but the bombs now do -100 blum points.

**Comment by belloabdul0** [comment]
Please can someone teach me how to set it up on my PC, I'm a newbie

**Comment by Wokzy** [comment]
I'm working on it

**Comment by Wokzy** [comment]
Update is ready. It is not perfect due to performance issues, I wrote about it in README.md
