### ISSUE TITLE
Daily Check-In Not Registering for 3 Days

### ISSUE THREAD

**Issue by kero7395** [Wokzy/blum-bot#7]
Hello,

I've noticed that for the past three days, the daily check-in hasn't been registering in the Blum bot. As a result, I'm not receiving my tickets, and my streak has been reset. Could you please look into this issue?

Thank you!

**Comment by Wokzy** [comment]
Hello. My bot isnt registering daily check-ins, it merely clicks on green "flowers" in drop game, what it was designed for)
