### ISSUE TITLE
Script crash

### ISSUE THREAD

**Issue by Kavindu-Wijesekara** [Wokzy/blum-bot#9]
Run `python main.py` and got this,

`
Trying to detect running game, click play
Traceback (most recent call last):
  File "D:\Projects\New folder\blum-bot\main.py", line 125, in <module>
    main()
  File "D:\Projects\New folder\blum-bot\main.py", line 80, in main
    wait_running_game(camera)
  File "D:\Projects\New folder\blum-bot\main.py", line 56, in wait_running_game
    application_bbox = prepare_app()
                       ^^^^^^^^^^^^^
  File "D:\Projects\New folder\blum-bot\prepare_app.py", line 23, in prepare_app
    win32gui.SetForegroundWindow(hwnd)
pywintypes.error: (0, 'SetForegroundWindow', 'No error message is available')`

**Comment by Kavindu-Wijesekara** [comment]
Okay I got it. Is there way to limit the clicks? I mean a real human can't to click the all the stars.

**Comment by Wokzy** [comment]
You can try to add `time.sleep` in internal loop

```   
......
		while check_running(frame, application_bbox) or (datetime.datetime.now() - __timer).total_seconds() < AVG_GAME_DURATION:

			for x in x_range:
				for y in y_range:
					if check_object(frame[y][x]):
						mouse.move(x, y, absolute=True)
						mouse.click(button='left')
						
                        # >>>>>>> somewhere here  <<<<<<<<<<<<<<<<<<<<<<<<
                        # time.sleep(0.1)
			frame = camera.get_latest_frame()
......
```

**Comment by wwwwvwwwwvvwwwvw** [comment]
> Okay I got it. Is there way to limit the clicks? I mean a real human can't to click the all the stars.

how did you get it fixed? I am experiencing the same issue

**Comment by Kavindu-Wijesekara** [comment]
> Commenting first message: this error seems to be windows internal, If it frequently occurs, try to run the script as Administrator
> 
> You can try to add `time.sleep` in internal loop to slow down click speed. The script itself doesn't recognize "stars", it siply clicks on every "green" pixel, so, limiting amount of stars to be collected is not possible in my implementation
> 
> ```
> ......
> 		while check_running(frame, application_bbox) or (datetime.datetime.now() - __timer).total_seconds() < AVG_GAME_DURATION:
> 
> 			for x in x_range:
> 				for y in y_range:
> 					if check_object(frame[y][x]):
> 						mouse.move(x, y, absolute=True)
> 						mouse.click(button='left')
> 						
>                         # >>>>>>> somewhere here  <<<<<<<<<<<<<<<<<<<<<<<<
>                         # time.sleep(0.1)
> 			frame = camera.get_latest_frame()
> ......
> ```

Thanks I added `time.sleep(random.uniform(0.1, 1))` now total bulms count is random every time.

**Comment by Kavindu-Wijesekara** [comment]
> > Okay I got it. Is there way to limit the clicks? I mean a real human can't to click the all the stars.
> 
> how did you get it fixed? I am experiencing the exact same issue

I just run the script and press play as soon as possible. I know it is not a permanent fix. But we can define the number of games we want to play like this `python main.py 10` before starting the script. So, it will not a problem at all.
